site_name: API Documentation
site_url: https://www.tw-applicatiebouw.nl/portfolio/apidoc/
theme:
  name: material
  palette:
    primary: teal
  features: 
    - navigation.expand
nav:
  - 'API Reference': 'index.md'
  # - 'Getting started':
  #   - 'Set up': 'setup.md'
  #   - 'Quick start': 'quickstart.md'
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences 


